[[plugins]]
repo = 'vim-scripts/mru.vim'
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
   let g:deoplete#enable_at_startup = 1
   let g:deoplete#enable_ignore_case = 1
'''
[[plugins]]
repo = 'roxma/nvim-yarp'
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'itchyny/vim-gitbranch'
[[plugins]]
repo = 'maximbaz/lightline-ale'
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'szw/vim-tags'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'kien/ctrlp.vim'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'tpope/vim-rails'
[[plugins]]
repo = 'majutsushi/tagbar'
[[plugins]]
# 自動で閉じる
repo = 'tpope/vim-endwise'
[[plugins]]
# ドキュメント参照
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
[[plugins]]
repo = 'ryanolsonx/vim-lsp-javascript'
[[plugins]]
repo = 'ryanolsonx/vim-lsp-python'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
[[plugins]]
repo = 'natebosch/vim-lsc'
[[plugins]]
repo = 'elixir-lang/vim-elixir'
[[plugins]]
repo = "slim-template/vim-slim"
[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'othree/yajs.vim'
[[plugins]]
repo = 'posva/vim-vue'
[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'digitaltoad/vim-pug'
[[plugins]]
repo = 'mxw/vim-jsx'
