[[plugins]]
repo = 'vim-scripts/mru.vim'
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'pmsorhaindo/syntastic-local-eslint.vim'
[[plugins]]
repo = 'gcorne/vim-sass-lint'
[[plugins]]
repo = 'szw/vim-tags'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'Shougo/neocomplete.vim'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'kien/ctrlp.vim'
[[plugins]]
repo = 'scrooloose/nerdtree'
[[plugins]]
repo = 'tpope/vim-rails'
[[plugins]]
repo = 'majutsushi/tagbar'
[[plugins]]
# 自動で閉じる
repo = 'tpope/vim-endwise'
[[plugins]]
# ドキュメント参照
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'yuku-t/vim-ref-ri'
[[plugins]]
repo = 'fatih/vim-go'
[[plugins]]
repo = 'elixir-lang/vim-elixir'
[[plugins]]
repo = 'kchmck/vim-coffee-script'
[[plugins]]
repo = "slim-template/vim-slim"
[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = "ctrlpvim/ctrlp.vim"
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'othree/yajs.vim'
[[plugins]]
repo = 'posva/vim-vue'
[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
[[plugins]]
repo = 'Shougo/context_filetype.vim'
[[plugins]]
repo = 'digitaltoad/vim-pug'
[[plugins]]
repo = 'mxw/vim-jsx'
