[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/neosnippet.vim'
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'itchyny/vim-gitbranch'
[[plugins]]
repo = 'w0rp/ale'
[[plugins]]
repo = 'maximbaz/lightline-ale'
[[plugins]]
repo = 'szw/vim-tags'
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'kien/ctrlp.vim'
[[plugins]]
repo = 'preservim/nerdtree'
[[plugins]]
repo = 'majutsushi/tagbar'
[[plugins]]
# 自動で閉じる
repo = 'tpope/vim-endwise'
[[plugins]]
# ドキュメント参照
repo = 'thinca/vim-ref'
[[plugins]]
repo = 'natebosch/vim-lsc'
[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# Programing Languages
[[plugins]]
repo = 'digitaltoad/vim-pug'
[[plugins]]
repo = 'othree/yajs.vim'
[[plugins]]
repo = 'mxw/vim-jsx'
[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
[[plugins]]
repo = 'hashivim/vim-terraform'

# terraform-lsp
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'


# Language Servers
[[plugins]]
repo = 'ryanolsonx/vim-lsp-javascript'
[[plugins]]
repo = 'ryanolsonx/vim-lsp-python'
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
